# Generated by Django 2.2 on 2021-12-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.CharField(default='https://image.freepik.com/free-vector/mountaineering-logo-template_1126-55.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_summary',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=100),
        ),
    ]
