# Generated by Django 2.2 on 2021-12-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0003_auto_20211213_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('author', models.CharField(max_length=100)),
                ('article', models.TextField(max_length=2000)),
                ('image', models.CharField(default='https://image.freepik.com/free-vector/mountaineering-logo-template_1126-55.jpg', max_length=500)),
            ],
        ),
    ]
